### PR TITLE
Update README.md - add instructions for Nix

### PR DESCRIPTION
**Pull request by drupol**
Add a section to show how to use it with Nix

### CODE REVIEW

**Comment by superphil0** [comment]
Hi Drupol, thank you for integration open-pdf-sign in Nix so quickly!  We would love to link to nix and also provide instructions on how to use it. However, this pull request sounds more like an advertisment for Nix.

Please shorten your suggestion to 2-3 lines and we will be happy to include them as well as a link to Nix

**Comment by drupol** [comment]
> Hi Drupol, thank you for integrating open-pdf-sign in Nix so quickly! We would love to link to nix and also provide instructions on how to use it. However, this pull request sounds more like an advertisment for Nix.
> 
> Please shorten your suggestion to 2-3 lines and we will be happy to include them as well as a link to Nix

I understand. I usually add more information regarding Nix since this is not something common (yet!).

**Comment by drupol** [comment]
@superphil0 I updated the patch and fixed the conflict. I removed superfluous Nix things and kept the things to the bare minimum. Hope it's ok.

**Comment by cproof** [comment]
Hi @drupol ,
thank you for submitting open-pdf-sign to nix and updating the PR!

As at this time, we're still only really instructing on the minimum (i.e. curl package), we'd refrain from adding much more text to the README as it's already quite long. I've tried to link to the nix package [in the dev branch's](https://github.com/open-pdf-sign/open-pdf-sign/commit/c717a457fcaf31bc7cc87d73f83df815b6682b45) [README](https://github.com/open-pdf-sign/open-pdf-sign/blob/dev/README.md) and hope that's ok with you for the moment. (Will merge dev to master shortly)

**Comment by drupol** [comment]
You're welcome :)

I would say that having a README which is big is not an issue as long as it is properly structured.

Anyway, I let you do as you wish.

**Pull request closed without merging**
